// <auto-generated />
namespace OpenRailData.Schedule.NetworkRailScheduleDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LocationName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LocationName));
        
        string IMigrationMetadata.Id
        {
            get { return "201602271527087_LocationName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
