// <auto-generated />
namespace OpenRailData.Schedule.NetworkRailScheduleDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ScheduleLocationCascadeDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ScheduleLocationCascadeDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201602160006485_ScheduleLocationCascadeDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
